version: '3'

services:
    app:
        build: .
        image: aokpower/id_lookup_app:1.0
        ports:
            - 9292:9292
        volumes:
            - ./logs:/app/logs
        environment:
            - IDL_REDIS_HOST=redis
        links:
            - redis
    redis:
        image: redis:latest
        expose:
            - 6379

